# Generated by Django 3.2.8 on 2021-10-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('controle', models.CharField(max_length=30, null=True)),
                ('validade_ca', models.DateTimeField(null=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Material'), ('1', 'EPI')], max_length=1)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.SmallIntegerField(default=0)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Material'), ('1', 'EPI')], max_length=1)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=30, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('localizacao', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('localizacao', models.CharField(max_length=100, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
                ('id_pessoa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('localizacao', models.CharField(max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
            ],
        ),
    ]
