# Generated by Django 3.2.8 on 2021-11-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('controle', models.CharField(max_length=30, null=True)),
                ('validade_ca', models.DateField(null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.SmallIntegerField(default=0)),
                ('tipo', models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=30, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('localizacao', models.CharField(default='--', max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('localizacao', models.CharField(default='--', max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
                ('id_pessoa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.pessoas')),
            ],
        ),
        migrations.AddField(
            model_name='lotes',
            name='id_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais'),
        ),
        migrations.CreateModel(
            name='Historico_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('localizacao', models.CharField(default='--', max_length=100)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('id_lote', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.lotes')),
                ('id_material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais')),
            ],
        ),
    ]
