# Generated by Django 3.2.8 on 2021-10-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='controle',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
