# Generated by Django 3.2.8 on 2021-11-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historico_material',
            name='localizacao',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='validade_ca',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='localizacao',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='situacao_material',
            name='localizacao',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
