# Generated by Django 3.2.8 on 2021-11-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0002_auto_20211104_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotes',
            old_name='material',
            new_name='id_material',
        ),
    ]
