# Generated by Django 3.2.8 on 2021-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0002_auto_20211029_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='controle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='validade_ca',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='situacao_material',
            name='localizacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
