# Generated by Django 3.2.8 on 2021-10-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0006_alter_historico_material_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='localizacao',
            field=models.CharField(default='--', max_length=100),
        ),
    ]
