# Generated by Django 3.2.8 on 2021-11-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0009_auto_20211029_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotes',
            name='material',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais'),
        ),
    ]
