# Generated by Django 3.2.8 on 2021-11-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estoque', '0010_lotes_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotes',
            name='material',
            field=models.ForeignKey(blank=True, default='2', on_delete=django.db.models.deletion.CASCADE, to='gestao_estoque.materiais'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Material', 'Material'), ('EPI', 'EPI')], max_length=8),
        ),
    ]
